# render.yaml
services:
  - type: web
    name: lifelens-backend
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: ELEVENLABS_VOICE_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: TRUSTED_CONTACT_NUMBER
        sync: false